name: GitHub Actions deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      # npm install
      - name: npm install and build 🔧
        run: |
          npm install
          npm run build
        env:
          CI: true
      # Deploy
      - name: Git Push Action
        uses: x-actions/git-push@v1
        env:
          GITHUB_EMAIL: "1172258408@qq.com"
          GITHUB_USERNAME: "liuzhiyan5"
          PUBLISH_REPO: https://${{ secrets.PAT }}@github.com/liuzhiyan5/Mou_Blog.git
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
